spring:
  application:
    name: AuthService
  cloud:
    config:
      name: auth-service
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 5
        max-interval: 5000
        multiplier: 1.2
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.boot.context.config: TRACE