server:
  port: 8085

spring:
  application:
    name: auth-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 8282838492923945986034034
  expiration: 3600