
services:
  postgres:
    image: postgres:latest
    container_name: postgres-card-service
    environment:
      POSTGRES_DB: card_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: changeme
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
