services:
  mysql_user_service:
    container_name: mysql_user_service
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: user_service
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_user_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - back_network
  
  mysql_account_service:
    container_name: mysql_account_service
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account_db
      MYSQL_USER: account_service
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_account_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - back_network
  
  postgres_keycloak:
    container_name: postgres_keycloak
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  # Cambiado de 5432 a 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - back_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -d keycloak_db" ]
      interval: 30s
      timeout: 5s
      retries: 5
  
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/keycloak_db  # Este mantiene 5432 porque es interno
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    ports:
      - "9092:8080"
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    networks:
      - back_network

volumes:
  mysql_user_data:
  mysql_account_data:
  postgres_data:

networks:
  back_network:
    driver: bridge