server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Auth Service Routes
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        
        # User Service Routes
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        
        # Account Service Routes
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/accounts/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        
        # Transaction Service Routes
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/transactions/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        
        # Card Service Routes
        - id: card-service
          uri: lb://CARD-SERVICE
          predicates:
            - Path=/api/cards/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /v3/api-docs
        name: API Gateway
      - url: /auth-service/v3/api-docs
        name: Auth Service
      - url: /user-service/v3/api-docs
        name: User Service
      - url: /account-service/v3/api-docs
        name: Account Service
      - url: /transaction-service/v3/api-docs
        name: Transaction Service
      - url: /card-service/v3/api-docs
        name: Card Service

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.dmh.gateway: DEBUG