server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Documentation Routes
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        
        # Auth Service Routes
        - id: auth-service-swagger
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/v3/api-docs/**
          filters:
            - RewritePath=/auth-service/v3/api-docs/(?<path>.*), /api/v3/api-docs
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        
        # User Service Routes
        - id: user-service-swagger
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v3/api-docs/**
          filters:
            - RewritePath=/user-service/v3/api-docs/(?<path>.*), /api/v3/api-docs
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        
        # Account Service Routes
        - id: account-service-swagger
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account-service/v3/api-docs/**
          filters:
            - RewritePath=/account-service/v3/api-docs/(?<path>.*), /api/v3/api-docs
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/accounts/**
        
        # Transaction Service Routes
        - id: transaction-service-swagger
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transaction-service/v3/api-docs/**
          filters:
            - RewritePath=/transaction-service/v3/api-docs/(?<path>.*), /api/v3/api-docs
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/transactions/**
        
        # Card Service Routes
        - id: card-service-swagger
          uri: lb://CARD-SERVICE
          predicates:
            - Path=/card-service/v3/api-docs/**
          filters:
            - RewritePath=/card-service/v3/api-docs/(?<path>.*), /api/v3/api-docs
        - id: card-service
          uri: lb://CARD-SERVICE
          predicates:
            - Path=/api/cards/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Gateway API
      - url: /api/v3/api-docs/auth-service
        name: Auth Service
      - url: /api/v3/api-docs/user-service
        name: User Service
      - url: /api/v3/api-docs/account-service
        name: Account Service
      - url: /api/v3/api-docs/transaction-service
        name: Transaction Service
      - url: /api/v3/api-docs/card-service
        name: Card Service
    disable-swagger-default-url: true
    display-request-duration: true
    deep-linking: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.dmh.gateway: DEBUG

# CORS Configuration
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
  allow-credentials: true
  max-age: 3600