spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  cloud:
    discovery:
      enabled: true
    config:
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000
    compatibility-verifier:
  
  # Adding the security configuration for JWT
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:9092/realms/dmh}  # Adjust this URL based on your auth server

# Your existing actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"