server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-register-service
          uri: lb://USER-REGISTER-SERVICE
          predicates:
            - Path=/register/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: generate-cvu-service
          uri: lb://GENERATE-CVU
          predicates:
            - Path=/Cvu/**
        - id: generate-alias-service
          uri: lb://GENERATE-ALIAS
          predicates:
            - Path=/generate-alias/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"