services:
  postgres:
    image: postgres:latest
    container_name: postgres_transaction_db
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: changeme
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
