server:
  port: 8088

spring:
  application:
    name: GenerateCvuGit
  cloud:
    config:
      enabled: false
      
  eureka:
    client:
      register-with-eureka: {EUREKA_REGISTER_WITH_EUREKA:true}
      fetch-registry: {EUREKA_FETCH_REGISTRY:true}
      service-url:
        defaultZone: {EUREKA_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    root: INFO
    com.dmh.GenerateCvu: DEBUG
    org.springframework: INFO
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: TRACE
    org.springframework.cloud: DEBUG


