spring:
  application:
    name: account-service
  cloud:
    config:
      enabled: false  # Deshabilitar config server temporalmente
  datasource:
    url: jdbc:postgresql://localhost:5432/dmh_account_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8082
  servlet:
    context-path: /api

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true