services:
  account-service-db:
    image: postgres:latest
    container_name: account-service-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: dmh_account
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - account_service_data:/var/lib/postgresql/data
    networks:
      - dmh-network

volumes:
  account_service_data:
    name: dmh_account_postgres_data

networks:
  dmh-network:
    name: dmh-network