
services:
  postgres:
    image: postgres:latest
    container_name: dmh_account_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-dmh_account_db}
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-user} -d ${DB_DATABASE:-dmh_account_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: