

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: 'userservice_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'changeme'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: