
spring:
  application:
    name: GenerateCvu
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: false
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 100
    discovery:
      enabled: true


