server:
  port: 8089



spring:
  application:
    name: GenerateCvu

  cloud:
    config:
      enabled: false

  eureka:
    client:
      register-with-eureka: {EUREKA_REGISTER_WITH_EUREKA:true}
      fetch-registry: {EUREKA_FETCH_REGISTRY:true}
      service-url:
        defaultZone: {EUREKA_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: ${MANAGEMENT_ENDPOINT_ENV_POST_ENABLED:true}

