server:
  port: ${SERVER_PORT_CONFIG_SERVER:8888}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME_CONFIG_SERVER:config-server}
  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI:}
          host-key-algorithm: ssh-rsa
          private-key: ${SPRING_CLOUD_CONFIG_SERVER_GIT_PRIVATE_KEY:}

eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:true}
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: ${MANAGEMENT_ENDPOINT_ENV_POST_ENABLED:true}

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG