spring:
  application:
    name: GenerateAlias
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:}
  cloud:
    config:
      fail-fast: false

