spring:
  application:
    name: ${SPRING_APPLICATION_NAME_GENERATE_ALIAS:}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  cloud:
    config:
      fail-fast: false