spring:
  application:
    name: ${SPRING_APPLICATION_NAME_GENERATE_ALIAS:}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:}
  cloud:
    config:
      fail-fast: false